### ISSUE TITLE
TCA library deadlocks when i2c device fails 

### ISSUE THREAD

**Issue by WouterSchols** [adafruit/Adafruit_CircuitPython_TCA9548A#29] opened 2021-03-31 10:46 UTC
When the TCA is connected to the i2c device and the device throws an OSError then the TCA library has a chance to deadlock. I am unable to reproduce this error without the TCA library.

```
Traceback (most recent call last):
  File "RowTest1.py", line 32, in <module>
    res += "|O" if square.value == False else "|X"  # Reads value of sensor square over i2c
  File "/home/pi/SmartChessboard/env/lib/python3.7/site-packages/adafruit_mcp230xx/digital_inout.py", line 80, in value
    return _get_bit(self._mcp.gpio, self._pin)
  File "/home/pi/SmartChessboard/env/lib/python3.7/site-packages/adafruit_mcp230xx/mcp23017.py", line 63, in gpio
    return self._read_u16le(_MCP23017_GPIOA)
  File "/home/pi/SmartChessboard/env/lib/python3.7/site-packages/adafruit_mcp230xx/mcp230xx.py", line 36, in _read_u16le
    with self._device as i2c:
  File "/home/pi/SmartChessboard/env/lib/python3.7/site-packages/adafruit_bus_device/i2c_device.py", line 137, in __enter__
    while not self.i2c.try_lock():
  File "/home/pi/SmartChessboard/env/lib/python3.7/site-packages/adafruit_tca9548a.py", line 47, in try_lock
    while not self.tca.i2c.try_lock():
KeyboardInterrupt
```

The issue: https://github.com/adafruit/Adafruit_CircuitPython_TCA9548A/issues/8 describes the exact same issue. This issue was resolved by the user by simply not using the TCA. Unfortunately this is not an option for me. Furthermore simply adding a sleep time before the next i2c request does not avoid the deadlock

**Comment by caternuson** [comment] 2021-03-31 15:31
The logic was based on what the `BusDevice` library does:

https://github.com/adafruit/Adafruit_CircuitPython_BusDevice/blob/60686e1e30684b895d2aebf15f888c5d73d8eceb/adafruit_bus_device/i2c_device.py#L136-L139

So the same issue could potentially be there as well. You say you can't reproduce this without the TCA library. Is that by skipping the TCA and wiring directly?

**Comment by WouterSchols** [comment] 2021-03-31 16:05
Yes that is by skipping the TCA and just wiring it directly

**Comment by WouterSchols** [comment] 2021-04-10 15:45
I have looked into the code and tried to trace the error. I am quite puzzled by why I can only reproduce it with the TCA and I could not find a easy and simple solution to permanently fix the problem. I have found two workarounds which work for me. If other people encounter these errors I would try one of these temporary fixes. 

1. The first solution is reinstantiating the instances of _busio.I2C_, _adafruit_tca9548a.TCA9548A_ and all i2c devices after the error. This is an easy and safe solution but it is very tedious if your setup is large and the code is complex.
2. The second solution is setting the variable _tca.i2c.\_locked_ to _False_. Here _tca_ is a _adafruit\_tca9548a.TCA9548A_ instance. This solution works for me without problems however this is obviously more of a hack than a solution.

**Comment by caternuson** [comment] 2021-05-24 23:29
I think maybe the bus state was locked at the time of the exception and does not get unlocked. So that persists to the next use and ends up getting stuck waiting for an unlock that never happens. Could also try adding a call to `i2c.unlock()`. That'd be similar to your 2nd approach above.

**Comment by caternuson** [comment] 2023-11-10 18:29
Looking at this again, not sure why/where unlock is not getting called. The `__exit__` should still get called if an exception occurs in the context manager, and that calls unlock.

Can you provide a simple test code for this? So we can try and reproduce it locally.

**Comment by caternuson** [comment] 2024-02-02 17:08
Closing for now. Can reopen if example provided.

**Closed as completed by caternuson** 2024-02-02 17:08 UTC
